# Generated by Django 4.2 on 2025-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='collar_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='puppy',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='distinctive_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='has_collar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puppy',
            name='has_microchip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puppy',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
